version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/deepsourcelabs/hermes"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true